name: Run Python Test

on:
  workflow_call:

env:
  PYTHONPATH: ${{ github.workspace }}

jobs:
  Run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"

      - run: | # To fetch all history for all tags and branches
          git fetch --prune --unshallow

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12 # Modify python version HERE

      #Task for installing dependencies, multi-line command
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install black pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Task for linting with black
      - name: Lint with black
        run: |
          # Code formatting with black, check every python file in the src directory 
          black --check --diff src

      - name: Download THDc gRPC classes
        run: |
          curl -s -L -o thdcgrpc.tar.gz https://github.com/THD-C/Protocol/releases/latest/download/thdcgrpc.tar.gz \
          && tar -xzf thdcgrpc.tar.gz \
          && rm thdcgrpc.tar.gz \
          && cp -r thdcgrpc/* . \
          && rm -r thdcgrpc

      # Task for testing with pytest
      - name: Test with pytest
        run: |
          pytest
